'use client'

import { useState, useEffect } from 'react'
import { useParams, useSearchParams, useRouter } from 'next/navigation'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Textarea } from '@/components/ui/textarea'
import { Badge } from '@/components/ui/badge'
import { 
  ArrowLeft, 
  Palette, 
  Loader2, 
  ExternalLink, 
  Sparkles,
  FileText,
  Wand2
} from 'lucide-react'
import Link from 'next/link'

interface Feature {
  id: number
  title?: string
  description?: string
  'drive-link': string
  'v0-link': string
  user: string
}

// Helper function to generate design prompt from PRD content
const generateDesignPromptFromPRD = (feature: Feature, prdContent: string): string => {
  const title = feature.title || `Feature #${feature.id}`
  const description = feature.description || ''
  
  // Extract key information from PRD
  const prdLines = prdContent.split('\n').filter(line => line.trim())
  const objectives = prdLines.filter(line => 
    line.toLowerCase().includes('objective') || 
    line.toLowerCase().includes('goal') ||
    line.toLowerCase().includes('purpose')
  ).slice(0, 2)
  
  const userStories = prdLines.filter(line => 
    line.toLowerCase().includes('user') || 
    line.toLowerCase().includes('customer') ||
    line.toLowerCase().includes('as a')
  ).slice(0, 3)

  const requirements = prdLines.filter(line => 
    line.toLowerCase().includes('requirement') || 
    line.toLowerCase().includes('must') ||
    line.toLowerCase().includes('should')
  ).slice(0, 3)

  return `Create a modern, professional SaaS interface for "${title}".

${description ? `Feature Overview: ${description}` : ''}

${objectives.length > 0 ? `Key Objectives:\n${objectives.map(obj => `• ${obj.trim()}`).join('\n')}\n` : ''}

${userStories.length > 0 ? `User Stories:\n${userStories.map(story => `• ${story.trim()}`).join('\n')}\n` : ''}

${requirements.length > 0 ? `Key Requirements:\n${requirements.map(req => `• ${req.trim()}`).join('\n')}\n` : ''}

Design Guidelines:
• Clean, modern interface with intuitive navigation
• Professional SaaS application aesthetic
• Clear visual hierarchy and consistent spacing
• Accessible design with proper contrast and typography
• Responsive layout optimized for desktop use
• Include relevant interactive elements and clear CTAs
• Focus on the primary user workflow

Please create a complete, functional interface that demonstrates the core user experience.`
}

// Fallback prompt when PRD parsing fails
const generateFallbackPrompt = (feature: Feature): string => {
  return `Create a modern, professional SaaS interface for "${feature.title || `Feature #${feature.id}`}".

${feature.description ? `Description: ${feature.description}` : ''}

Design Guidelines:
• Clean, modern interface with intuitive navigation
• Professional SaaS application aesthetic  
• Clear visual hierarchy and consistent spacing
• Accessible design with proper contrast and typography
• Responsive layout optimized for desktop use
• Include relevant interactive elements and clear CTAs

Please create a complete, functional interface that demonstrates the core user experience.`
}

export default function FeatureDesignPage() {
  const params = useParams()
  const searchParams = useSearchParams()
  const router = useRouter()
  const featureId = params.id as string
  
  const [feature, setFeature] = useState<Feature | null>(null)
  const [loading, setLoading] = useState(true)
  const [generating, setGenerating] = useState(false)
  const [autoGenerating, setAutoGenerating] = useState(false)
  const [designPrompt, setDesignPrompt] = useState('')
  const [prdContent, setPrdContent] = useState('')
  const [v0Result, setV0Result] = useState<{
    chatId?: string
    chatUrl?: string
    demoUrl?: string
  } | null>(null)

  // Load feature data
  useEffect(() => {
    const fetchFeature = async () => {
      try {
        const response = await fetch(`/api/roadmap/prd/${featureId}`)
        if (response.ok) {
          const data = await response.json()
          setFeature(data)
          
          // Pre-populate design prompt based on feature
          if (data.title && data.description) {
            setDesignPrompt(`Create a modern, user-friendly interface for "${data.title}". 

Key requirements:
- ${data.description}
- Intuitive navigation and clear visual hierarchy
- Professional SaaS application design
- Responsive layout that works on desktop and mobile

Please focus on the main user workflow and create a clean, accessible design.`)
          }
        }
      } catch (error) {
        console.error('Error fetching feature:', error)
      } finally {
        setLoading(false)
      }
    }

    fetchFeature()
  }, [featureId])

  // Auto-generate design when feature and PRD are loaded
  useEffect(() => {
    const autoGenerateDesign = async () => {
      if (!feature?.['drive-link'] || autoGenerating || v0Result) return

      setAutoGenerating(true)
      
      try {
        // Step 1: Fetch PRD content
        const docIdMatch = feature['drive-link'].match(/\/d\/([a-zA-Z0-9-_]+)/)
        if (!docIdMatch) {
          throw new Error('Invalid Google Doc link format')
        }

        const prdResponse = await fetch('/api/get-google-doc-content', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ docId: docIdMatch[1] })
        })

        if (!prdResponse.ok) {
          throw new Error('Failed to fetch PRD content')
        }

        const prdData = await prdResponse.json()
        const fetchedPrdContent = prdData.content || ''
        setPrdContent(fetchedPrdContent)

        // Step 2: Generate intelligent design prompt from PRD
        const generatedPrompt = generateDesignPromptFromPRD(feature, fetchedPrdContent)
        setDesignPrompt(generatedPrompt)

        // Step 3: Start design generation immediately
        setGenerating(true)
        
        const designResponse = await fetch('/api/create-v0-chat', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            designPrompt: generatedPrompt,
            prdContent: fetchedPrdContent.substring(0, 2000),
            apiKey: process.env.NEXT_PUBLIC_V0_API_KEY
          })
        })

        if (!designResponse.ok) {
          const errorData = await designResponse.json()
          throw new Error(errorData.error || 'Failed to generate design')
        }

        const result = await designResponse.json()
        setV0Result(result)

        // Update feature with V0 link
        if (result.demoUrl) {
          await updateFeatureV0Link(result.demoUrl)
        }

      } catch (error) {
        console.error('Error in auto-generation:', error)
        // Set a fallback prompt so user can manually try
        setDesignPrompt(generateFallbackPrompt(feature))
      } finally {
        setAutoGenerating(false)
        setGenerating(false)
      }
    }

    autoGenerateDesign()
  }, [feature])

  const handleGenerateDesign = async () => {
    if (!designPrompt.trim()) {
      alert('Please enter a design prompt')
      return
    }

    setGenerating(true)
    try {
      const response = await fetch('/api/create-v0-chat', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          designPrompt,
          prdContent: prdContent.substring(0, 2000), // Limit PRD content
          apiKey: process.env.NEXT_PUBLIC_V0_API_KEY
        })
      })

      if (!response.ok) {
        const errorData = await response.json()
        throw new Error(errorData.error || 'Failed to generate design')
      }

      const result = await response.json()
      setV0Result(result)

      // Update feature with V0 link if we got a demo URL
      if (result.demoUrl) {
        await updateFeatureV0Link(result.demoUrl)
      }

    } catch (error) {
      console.error('Error generating design:', error)
      alert(`Failed to generate design: ${error.message}`)
    } finally {
      setGenerating(false)
    }
  }

  const updateFeatureV0Link = async (v0Link: string) => {
    try {
      const response = await fetch(`/api/roadmap/prd/${featureId}`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ 'v0-link': v0Link })
      })

      if (response.ok) {
        const updatedFeature = await response.json()
        setFeature(updatedFeature)
      }
    } catch (error) {
      console.error('Error updating feature V0 link:', error)
    }
  }

  if (loading) {
    return (
      <div className="min-h-screen bg-gradient-to-b from-poppy-primary-light/5 to-white flex items-center justify-center">
        <div className="text-center">
          <Loader2 className="w-8 h-8 animate-spin mx-auto mb-4" />
          <p>Loading feature...</p>
        </div>
      </div>
    )
  }

  if (!feature) {
    return (
      <div className="min-h-screen bg-gradient-to-b from-poppy-primary-light/5 to-white flex items-center justify-center">
        <div className="text-center">
          <p className="text-red-600">Feature not found</p>
          <Link href="/roadmap">
            <Button variant="outline" className="mt-4">
              <ArrowLeft className="w-4 h-4 mr-2" />
              Back to Roadmap
            </Button>
          </Link>
        </div>
      </div>
    )
  }

  return (
    <div className="min-h-screen bg-gradient-to-b from-poppy-primary-light/5 to-white">
      <div className="max-w-6xl mx-auto p-6">
        {/* Header */}
        <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-6 mb-6">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-4">
              <Link href={`/roadmap/feature/${featureId}`}>
                <Button variant="ghost" size="sm">
                  <ArrowLeft className="w-4 h-4 mr-2" />
                  Back to Feature
                </Button>
              </Link>
              <div>
                <h1 className="text-2xl font-bold text-poppy-primary flex items-center gap-2">
                  <Palette className="w-6 h-6" />
                  Design Generation
                </h1>
                <p className="text-warm-neutral">
                  Create AI-powered design mockups for "{feature.title || `Feature #${feature.id}`}"
                </p>
              </div>
            </div>
            {feature['v0-link'] && (
              <Badge variant="outline" className="bg-green-50 text-green-700 border-green-200">
                Design Ready
              </Badge>
            )}
          </div>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          {/* Left Column - Design Generation */}
          <div className="space-y-6">
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <Wand2 className="w-5 h-5 text-poppy-primary" />
                  Design Prompt
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    {autoGenerating ? 'Generating design prompt from your PRD...' : 'AI-Generated Design Prompt'}
                  </label>
                  <Textarea
                    value={designPrompt}
                    onChange={(e) => setDesignPrompt(e.target.value)}
                    placeholder={autoGenerating ? "Analyzing your PRD to create the perfect design prompt..." : "Your design prompt will appear here..."}
                    rows={8}
                    className="w-full"
                    disabled={autoGenerating}
                  />
                </div>

                {prdContent && (
                  <div className="bg-blue-50 border border-blue-200 rounded-lg p-3">
                    <div className="flex items-center gap-2 mb-2">
                      <FileText className="w-4 h-4 text-blue-600" />
                      <span className="text-sm font-medium text-blue-800">PRD Context Available</span>
                    </div>
                    <p className="text-xs text-blue-600">
                      Your PRD content will be included as context for better design generation
                    </p>
                  </div>
                )}

                {autoGenerating ? (
                  <div className="space-y-3">
                    <div className="bg-blue-50 border border-blue-200 rounded-lg p-4">
                      <div className="flex items-center gap-3 mb-2">
                        <Loader2 className="w-5 h-5 animate-spin text-blue-600" />
                        <span className="font-medium text-blue-800">🚀 Auto-generating your design...</span>
                      </div>
                      <div className="space-y-2 text-sm text-blue-700">
                        <div className="flex items-center gap-2">
                          <div className="w-2 h-2 bg-blue-400 rounded-full animate-pulse"></div>
                          Analyzing your PRD content
                        </div>
                        <div className="flex items-center gap-2">
                          <div className="w-2 h-2 bg-blue-400 rounded-full animate-pulse" style={{animationDelay: '0.5s'}}></div>
                          Creating intelligent design prompt
                        </div>
                        <div className="flex items-center gap-2">
                          <div className="w-2 h-2 bg-blue-400 rounded-full animate-pulse" style={{animationDelay: '1s'}}></div>
                          Generating design with V0 AI
                        </div>
                      </div>
                    </div>
                  </div>
                ) : (
                  <Button
                    onClick={handleGenerateDesign}
                    disabled={generating || !designPrompt.trim()}
                    className="w-full bg-poppy-primary hover:bg-poppy-primary-hover text-white"
                  >
                    {generating ? (
                      <>
                        <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                        Generating Design...
                      </>
                    ) : v0Result ? (
                      <>
                        <Wand2 className="w-4 h-4 mr-2" />
                        Regenerate Design
                      </>
                    ) : (
                      <>
                        <Sparkles className="w-4 h-4 mr-2" />
                        Generate Design with V0
                      </>
                    )}
                  </Button>
                )}

                {(generating || autoGenerating) && (
                  <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-3">
                    <p className="text-sm text-yellow-800">
                      ⏱️ Design generation may take 1-2 minutes. Please wait...
                    </p>
                  </div>
                )}
              </CardContent>
            </Card>
          </div>

          {/* Right Column - Preview/Results */}
          <div className="space-y-6">
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <Palette className="w-5 h-5 text-poppy-primary" />
                  Design Preview
                </CardTitle>
              </CardHeader>
              <CardContent>
                {v0Result?.demoUrl ? (
                  <div className="space-y-4">
                    <div className="w-full h-[400px] border rounded-lg overflow-hidden">
                      <iframe
                        src={v0Result.demoUrl}
                        className="w-full h-full"
                        title="Design Preview"
                      />
                    </div>
                    <div className="flex gap-2">
                      <Button variant="outline" size="sm" asChild>
                        <a href={v0Result.chatUrl} target="_blank" rel="noopener noreferrer">
                          <ExternalLink className="w-4 h-4 mr-2" />
                          Open in V0
                        </a>
                      </Button>
                      <Button 
                        size="sm"
                        onClick={() => router.push(`/roadmap/feature/${featureId}`)}
                      >
                        Save & Continue
                      </Button>
                    </div>
                  </div>
                ) : feature['v0-link'] ? (
                  <div className="space-y-4">
                    <div className="w-full h-[400px] border rounded-lg overflow-hidden">
                      <iframe
                        src={feature['v0-link']}
                        className="w-full h-full"
                        title="Existing Design"
                      />
                    </div>
                    <div className="bg-green-50 border border-green-200 rounded-lg p-3">
                      <p className="text-sm text-green-800">
                        ✅ This feature already has a design. Generate a new one to update it.
                      </p>
                    </div>
                  </div>
                ) : (
                  <div className="text-center py-12 text-gray-500">
                    <Palette className="w-12 h-12 mx-auto mb-3 text-gray-300" />
                    <p className="text-sm">Your generated design will appear here</p>
                  </div>
                )}
              </CardContent>
            </Card>
          </div>
        </div>
      </div>
    </div>
  )
}